In [6]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [7]:
data = pd.read_csv("tips.csv")
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [8]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

##it can be seen in this dataset that it has columns like total bill, sex of customer ,
#whether he is smoker or non smoker, the day of the month , the time he had food, and the size indicates how many people were on the table

In [9]:
figure = px.scatter(data_frame = data, x = "total_bill" , y = "tip" ,size = "size" , color = "size" , trendline="ols")
figure.show()

In [10]:
figure = px.scatter(data_frame = data, x = "total_bill" , y = "tip" ,size = "size" , color = "total_bill" , trendline="ols")
figure.show()

In [11]:
figure = px.scatter(data_frame = data, x = "total_bill" , y = "tip" ,size = "size" , color = "day" , trendline="ols")
figure.show()

In [12]:
figure = px.scatter(data_frame = data, x = "total_bill" , y = "tip" ,size = "size" , color = "sex" , trendline="ols")
figure.show()

In [13]:
figure = px.scatter(data_frame = data, x = "total_bill" , y = "tip" ,size = "size" , color = "smoker" , trendline="ols")
figure.show()

In [14]:
figure = px.scatter(data_frame = data, x = "total_bill" , y = "tip" ,size = "size" , color = "time" , trendline="ols")
figure.show()

In [15]:
figure = px.pie(data, names = "day",values="tip",hole = 0.3)
figure.show()

people gave great tips on saturdays followed by sundays , whilst fridays were days of least tips

In [16]:
figure = px.pie(data , values = "tip" , names = "smoker",hole = 0.2)
figure.show()

around 62% of tips came from non smokers

In [17]:
figure = px.pie(data , names = 'time', values = 'tip' , hole = 0.5)
figure.show()

75% of tips came at dinner time whilst 25% tips came at lunch time

In [18]:
figure  = px.pie(data ,values = 'tip',names = 'sex' , hole = 0.6)
figure.show()

2/3 rd of tips came from male customers

In [19]:
data.head(5
)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
figure = px.pie(data, values = 'tip',names = 'size',hole = 0.4)
figure.show()

55% tips came when only 2 people were enjoying their food(maybe couples😁), and around 38% tips came when groups of 3 or 4 were having food , whilst least of tips came when a single person or group of 5 or 6 had food




Now came the machine learning part , Waiter tips prediction model

In [21]:
data["sex"] = data["sex"].map({"Female":0,"Male":1})
data["smoker"] = data["smoker"].map({"No": 0, "Yes": 1})
data["day"] = data["day"].map({"Thur": 0, "Fri": 1, "Sat": 2, "Sun": 3})
data["time"] = data["time"].map({"Lunch": 0, "Dinner": 1})

In [22]:
data.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    3     1     2
1       10.34  1.66    1       0    3     1     3
2       21.01  3.50    1       0    3     1     3
3       23.68  3.31    1       0    3     1     2
4       24.59  3.61    0       0    3     1     4

In [23]:
x = np.array(data[["total_bill","sex","smoker","day","time","size"]])
y = np.array(data["tip"])

In [24]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2,random_state=42)

In [25]:
model = LinearRegression()

In [26]:
model.fit(x_train,y_train)

LinearRegression()

In [27]:
#test_features = [["total_bill","sex","smoker","day","time","size"]]
features = np.array([[70,1,0,2,1,3]])
model.predict(features)

array([7.93012405])